# Generated by Django 5.2.5 on 2026-01-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiator',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='radiator',
            name='compatible_vehicles',
        ),
        migrations.RemoveField(
            model_name='radiator',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='radiator',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='radiator',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='radiator',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='date_received',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiator',
            name='part_type',
            field=models.CharField(choices=[('Radiator', 'Radiator'), ('Intercooler', 'Intercooler'), ('Fuel Tank', 'Fuel Tank')], default='Radiator', max_length=50),
        ),
        migrations.AddField(
            model_name='radiator',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='name',
            field=models.CharField(help_text='Radiator Name/Model', max_length=200),
        ),
    ]
