# Generated by Django 5.2.5 on 2026-01-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_radiator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiator',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
    ]
